example_response = [
  {"name":"peter","gender":"male","probability":"1.00","count":796},
  {"name":"peter","gender":"male","probability":"1.00","count":796},
  {"name":"lois","gender":"female","probability":"0.94","count":70},
  {"name":"lois","gender":"female","probability":"0.94","count":70},
  {"name":"lois","gender":"female","probability":"0.94","count":70},
  {"name":"lois","gender":"female","probability":"0.94","count":70},
  {"name":"lois","gender":"female","probability":"0.94","count":70},
  {"name":"stevie","gender":"male","probability":"0.63","count":39},
  {"name":"qwerty","gender":"null"},
  {"name":"qwerty","gender":"null"},
  {"name":"qwerty","gender":"null"},
  {"name":"qwerty","gender":"null"},
  {"name":"linkedin","gender":"null"},
]